kibot:
  version: 1

preflight:
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  - name: "position"
    comment: "position of the components for the pick & place machine"
    type: "position"
    dir: "gerbers"
    options:
      format: "CSV"
      units: "millimeters"
      separate_files_for_front_and_back: false
      only_smd: true
